# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path
# Note - The testing and checkstyle phases are disabled, because there is a CI pipeline which guarantees that the master branch is green at all times. Also this will reduce the time for the release process.
# However the dependency vulnerability check is still on, because there might be Sec-DBs update, between the release an the last CI pipelines.

name: Publish package to GitHub Packages

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: all-onto # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: ONTO_MVN_USER_REF
        server-password: ONTO_MVN_TOKEN_REF
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package -DskipTests -Dcheckstyle.skip --file pom.xml

    - name: Publish Packages
      run: mvn --batch-mode deploy -DskipTests -Dcheckstyle.skip -s $GITHUB_WORKSPACE/settings.xml
      env:
        ONTO_MVN_USER_REF: ${{ secrets.ONTO_MAVEN_REPO_USER }}
        ONTO_MVN_TOKEN_REF: ${{ secrets.ONTO_MAVEN_REPO_PASSWORD }}
